version: '3.1'

services:
  app:
    restart: unless-stopped
    image: badmuts/sprout:latest
    build: .

  db:
    restart: unless-stopped
    image: postgres:9.6.5-alpine

  redis:
      restart: unless-stopped
      image: redis:4-alpine