version: '3.1'

services:
  app:
    image: badmuts/sprout:development
    build:
      context: .
      dockerfile: Dockerfile-develop
    ports:
      - 3000:3000
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/vendor/bundle

  db:
    ports:
      - 5432:5432